---

- name: "Disable SELinux"
  selinux:
    state: disabled

- name: "Stop and disable firewalld"
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: upgrade all packages
  yum: name=* state=latest

- name: Check for reboot hint
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  register: reboot_hint


- name: Rebooting ...
  command: shutdown -r now "Reboot required for updated kernel"
  async: 0
  poll: 0
  become: yes
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting

- name: Wait for reboot...
  pause: seconds=45
  when: rebooting|changed
